name = "colder-api"
main = "workers/index.ts"
compatibility_date = "2024-10-14"
node_compat = true

[build]
command = "pnpm build:worker"

[env.production]
vars = { DEFAULT_MODEL = "google/gemini-2.0-flash" }

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "your_kv_namespace_id"

# Secrets (set via wrangler secret put)
# SUPABASE_URL
# SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# SUPABASE_JWT_SECRET
# OPENROUTER_API_KEY
# DATABASE_URL

# Optional: D1 Database (SQLite alternative to PostgreSQL)
# [[d1_databases]]
# binding = "DB"
# database_name = "colder-db"
# database_id = "your_d1_database_id"